//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::booking::Entity as Booking;
pub use super::reminder::Entity as Reminder;
pub use super::room::Entity as Room;
pub use super::room_time_slots::Entity as RoomTimeSlots;
pub use super::strike::Entity as Strike;
pub use super::user::Entity as User;
