[build]
build = "nixpacks"

[deploy]
startCommand = "sea-orm-cli migrate up && ./target/release/fairroom"
healthcheckPath = "/health_check"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
